name: cwic_second
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  intl: ^0.18.0
  country_list_pick: ^1.0.1+6
  country_picker: ^2.0.19
  dropdown_button2: ^1.9.2
  currency_picker: ^2.0.13
  firebase_core: ^2.4.1
  http: ^0.13.5
  email_validator: ^2.1.17
  loading_indicator: ^3.1.0
  image_picker: ^0.8.6+1
  google_sign_in: ^5.4.4
  firebase_auth: ^4.2.2
  cloud_firestore: ^4.2.0
  shared_preferences: ^2.0.17
  google_maps_flutter: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf